copy new MEV file to NFSDIR, with a timeout TO [default:20s] report result to $NFSDIR/latest remove file from /tmp
Incorporates "multievent_wingman.sh" functionality

 On branch main
	modified:   bin/mev_nfs_mon

diff --git a/bin/mev_nfs_mon b/bin/mev_nfs_mon
--- a/bin/mev_nfs_mon
+++ b/bin/mev_nfs_mon
@@ -2,10 +2,18 @@
 # mev_disk_mon
 
 NFSDIR=${1:-/mnt/nfs}
+TO=${2:-20}
 
 cd /tmp
-while [ 1 ]; do
-	find . -name event-*.dat -exec mv {} $NFSDIR/{} \;
-	sleep 2
-done
+inotifywait -q -m -e close_write /etc/acq400/1/multi_event_latest | 
+	while read -r filename event; do
+		filename=$(cat "$filename")
+		timeout $TO cp $filename $NFSDIR/
+		if [ $? -eq 0 ]; then
+			echo $filename > $NFSDIR/latest
+		else
+			echo "ERROR $? $filename" > $NFSDIR/latest
+		fi
+		rm $filename
+	done
 
