handles seq number 	modified:   bin/multi_event

diff --git a/bin/multi_event b/bin/multi_event
--- a/bin/multi_event
+++ b/bin/multi_event
@@ -2,17 +2,29 @@
 
 SF=/dev/shm/multi_event_settings
 
+MULTI_EVENT=100,100,10,37
 source $SF
+
+seq=${MULTI_EVENT##*,}
 
 if [ -z $1 ]; then
 	echo $MULTI_EVENT
 else
-	echo $1 | grep -q [0-9]*,[0-9]*,[0-9]*
+	echo $1 | grep -q [0-9]*,[0-9]*,[0-9]*,[0-9]*
+
 	if [ $? -eq 0 ]; then
-		echo "MULTI_EVENT=$1" > /dev/shm/multi_event_settings
+		# user supplied seq
+		echo "MULTI_EVENT=$1" > $SF
 	else
-		echo "ERROR INVALID DATA"
-		exit 1
+		echo $1 | grep -q [0-9]*,[0-9]*,[0-9]*
+		if [ $? -eq 0 ]; then
+			# auto seq .. preferred
+			seq=$((seq+1))
+			echo "MULTI_EVENT=$1,$seq" > $SF
+		else
+			echo "ERROR INVALID DATA"
+			exit 1
+		fi
 	fi
 fi
 
